name: Windup PR builder for JDK11

on:
  pull_request:
    branches:
      - master
      - 'releases/**'

jobs:

  windup-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: windup/windup
          ref: ${{ github.base_ref }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: jdk
          cache: 'maven'
      - name: Build on JDK 11
        run: mvn -B clean install -DskipTests

  WindupRulesTest:
    runs-on: ubuntu-latest
    needs: [windup-build]
    strategy:
      fail-fast: false
      matrix:
        jdk-distribution: [ temurin ]
        tests-pattern: [ 'rules-reviewed/[a-d]',
                         'rules-reviewed/eap6',
                         'rules-reviewed/eap7',
                         'rules-reviewed/eap8',
                         'rules-reviewed/eapxp',
                         'rules-reviewed/[eb-s]',
                         'rules-reviewed/technology-usage/tests/[0-9,a-i]',
                         'rules-reviewed/technology-usage/tests/[j-z]',
                         'rules-reviewed/[u-z]',
                         'rules-generated/' ]
        java-version: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.jdk-distribution }}
          java-package: jdk
          cache: 'maven'
      - name: Build
        run: mvn -B clean install -DskipTests
      - name: Test
        run: mvn -B test -f rules/ -DrunTestsMatching=${{ matrix.tests-pattern }} -Dtest=WindupRulesTest

  WindupRulesLinksTest:
    runs-on: ubuntu-latest
    needs: [windup-build]
    strategy:
        fail-fast: false
        matrix:
            jdk-distribution: [ temurin ]
            java-version: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.jdk-distribution }}
          java-package: jdk
          cache: 'maven'
      - name: Build
        run: mvn -B clean install -DskipTests
      - name: Test
        run: mvn -B test -f rules/ -Dtest=WindupRulesLinksTest


